Add list of team members to contact, fixes #71
digitalfabrik/ish-goalkeeper pull request #96
Opened 2021-09-29 13:41 UTC by JoeyStk

Add list of team members to contact, fixes #71

This is a new pull request for this issue

Please check:
- why the for loop doesn't work yet. I need some help
- if the Contact model is fine
- if I understood correctly this time

Thanks!

2022-05-21 12:05 UTC, JoeyStk commented
This push adds the telephone number and an avatar to the user model. Please let me know, if I altered the model correctly or if I should have added it to the foreign key. 
Should the image and the telephone number be shown in the template?

2022-07-06 13:16 UTC, svenseeberg requested changes
This pull request still needs some features before it is complete.

2022-07-06 13:16 UTC, svenseeberg commented on src/gui/templates/contact.html
> +        test
The `test` is probably not required anymore? ;-)

2022-07-06 13:16 UTC, svenseeberg commented on src/gui/templates/contact.html
> +      {% is_staff %}
Is `is_staff` defined anywhere? You probably need to iterate over all users and then check for the user attribute `is_staff`.

For example like this:
```
{% for user in author %}
{% if user.is_staff %}

render some HTML

{% endif %}
{% endfor %}
```

2022-07-06 13:16 UTC, svenseeberg commented on src/gui/templates/contact.html
> +        {% for user in author %}
What is `author`? I think you need to set the variable in the view first. That means that line https://github.com/digitalfabrik/ish-goalkeeper/blob/master/src/gui/views/contact.py#L16 needs a `context` being set as in https://github.com/digitalfabrik/ish-goalkeeper/blob/master/src/gui/views/contact.py#L32. The context needs to contain a list of existing users, over which you can then iterate in the template.

2022-07-18 14:46 UTC, svenseeberg commented on src/gui/templates/contact.html
> +      {{ user.avatar }}
Does it make sense to do a little more styling here? In this case we have everything in one line, right?

2022-07-29 12:17 UTC, merged